export const taskAttributes = [
  "id",
  "title",
  "important",
  "closeDate",
  "deadline",
  "description",
  "overtime",
  "pausal",
  "pendingChangable",
  "pendingDate",
  "statusChange",
  "invoicedDate",
  "invoiced",
  "createdAt",
  "updatedAt",
  "UserId",
  "ProjectId",
  "TaskTypeId",
  "CompanyId",
  "StatusId",
  "MilestoneId",
  "createdById",
  "requesterId",
  "RepeatId",
]

export const projectAttributes = [
  "id",
  "title",
  "description",
  "lockedRequester",
  "autoApproved",
  "defAssignedToDef",
  "defAssignedToFixed",
  "defAssignedToRequired",
  "defCompanyDef",
  "defCompanyFixed",
  "defCompanyRequired",
  "defOvertimeDef",
  "defOvertimeFixed",
  "defOvertimeRequired",
  "defOvertimeValue",
  "defPausalDef",
  "defPausalFixed",
  "defPausalRequired",
  "defPausalValue",
  "defRequesterDef",
  "defRequesterFixed",
  "defRequesterRequired",
  "defStatusDef",
  "defStatusFixed",
  "defStatusRequired",
  "defTagDef",
  "defTagFixed",
  "defTagRequired",
  "defTaskTypeDef",
  "defTaskTypeFixed",
  "defTaskTypeRequired",
  "createdAt",
  "updatedAt",
  "UserId",
  "defCompanyId",
  "defRequesterId",
  "defTaskTypeId",
  "TaskTypeId",
  "CompanyId",
]

export const taskAttachmentAttributes = [
  "id",
  "filename",
  "mimetype",
  "encoding",
  "createdAt",
  "updatedAt",
  "UserId",
  "TaskId",
  "path",
  "size",
]

export const userAttributes = [
  "id",
  "active",
  "username",
  "email",
  "name",
  "surname",
  "receiveNotifications",
  "signature",
  "language",
  "RoleId",
  "CompanyId",
]

export const companyAttributes = [
  "id",
  "title",
  "dph",
  "ico",
  "dic",
  "ic_dph",
  "email",
  "phone",
  "description",
  "monthly",
  "monthlyPausal",
  "taskWorkPausal",
  "taskTripPausal",
  "createdAt",
  "updatedAt",
  "PricelistId",
]

export const pricelistAttributes = [
  "id",
  "title",
  "order",
  "afterHours",
  "def",
  "materialMargin",
  "materialMarginExtra",
  "createdAt",
  "updatedAt",
]
export const priceAttributes = [
  "id",
  "price",
  "type",
  "createdAt",
  "updatedAt",
  "TaskTypeId",
  "TripTypeId",
  "PricelistId",
]
export const taskTypeAttributes = [
  "id",
  "title",
  "order",
  "createdAt",
  "updatedAt",
]
export const tripTypeAttributes = [
  "id",
  "title",
  "order",
  "createdAt",
  "updatedAt",
]

export const milestoneAttributes = [
  "id",
  "title",
  "description",
  "startsAt",
  "endsAt",
  "createdAt",
  "updatedAt",
  "ProjectId",
]

export const statusAttributes = [
  "id",
  "title",
  "order",
  "color",
  "icon",
  "action",
]
export const repeatAttributes = [
  "id",
  "repeatEvery",
  "repeatInterval",
  "startsAt",
  "active",
  "createdAt",
  "updatedAt",
]
export const taskMetadataAttributes = [
  "id",
  "subtasksApproved",
  "subtasksPending",
  "tripsApproved",
  "tripsPending",
  "materialsApproved",
  "materialsPending",
  "itemsApproved",
  "itemsPending",
  "createdAt",
  "updatedAt",
  "TaskId",
]

export const repeatTimeAttributes = [
  "id",
  "originalTrigger",
  "triggersAt",
  "triggered",
  "createdAt",
  "updatedAt",
  "RepeatId",
]

export const subtaskAttributes = [
  "id",
  "title",
  "order",
  "done",
  "approved",
  "quantity",
  "discount",
  "invoiced",
  "createdAt",
  "updatedAt",
  "UserId",
  "TaskTypeId",
  "TaskId",
  "RepeatTemplateId",
  "SubtaskApprovedById",
]

export const workTripAttributes = [
  "id",
  "order",
  "done",
  "approved",
  "quantity",
  "discount",
  "createdAt",
  "updatedAt",
  "UserId",
  "TripTypeId",
  "TaskId",
  "RepeatTemplateId",
  "TripApprovedById",
]
export const materialAttributes = [
  "id",
  "title",
  "order",
  "done",
  "approved",
  "quantity",
  "margin",
  "price",
  "createdAt",
  "updatedAt",
  "UserId",
  "TaskId",
  "RepeatTemplateId",
  "MaterialApprovedById",
]
export const customItemAttributes = [
  "id",
  "title",
  "order",
  "done",
  "approved",
  "quantity",
  "price",
  "createdAt",
  "updatedAt",
  "UserId",
  "TaskId",
  "RepeatTemplateId",
  "ItemApprovedById",
]

export const scheduledTaskAttributes = [
  "id",
  "createdAt",
  "updatedAt",
  "TaskId",
  "UserId",
  "from",
  "to"
]

export const scheduledWorkAttributes = [
  "id",
  "createdAt",
  "updatedAt",
  "from",
  "to"
]
