export const filterObjectToFilter = (Filter) => ({
  assignedToCur: Filter.assignedToCur,
  assignedTo: Filter.assignedTo === null ? null : Filter.assignedTo.get('id'),
  requesterCur: Filter.requesterCur,
  requester: Filter.requester === null ? null : Filter.requester.get('id'),
  companyCur: Filter.companyCur,
  company: Filter.company === null ? null : Filter.company.get('id'),
  taskType: Filter.taskType === null ? null : Filter.taskType.get('id'),
  oneOf: Filter.oneOf,

  statusDateFrom: Filter.statusDateFrom,
  statusDateFromNow: Filter.statusDateFromNow,
  statusDateTo: Filter.statusDateTo,
  statusDateToNow: Filter.statusDateToNow,
  pendingDateFrom: Filter.pendingDateFrom,
  pendingDateFromNow: Filter.pendingDateFromNow,
  pendingDateTo: Filter.pendingDateTo,
  pendingDateToNow: Filter.pendingDateToNow,
  closeDateFrom: Filter.closeDateFrom,
  closeDateFromNow: Filter.closeDateFromNow,
  closeDateTo: Filter.closeDateTo,
  closeDateToNow: Filter.closeDateToNow,
  deadlineFrom: Filter.deadlineFrom,
  deadlineFromNow: Filter.deadlineFromNow,
  deadlineTo: Filter.deadlineTo,
  deadlineToNow: Filter.deadlineToNow,
})
