export const filterObjectToFilter = (Filter) => ({
  assignedToCur: Filter.assignedToCur,
  assignedTos: Filter.assignedTos === null ? null : Filter.assignedTos.get('id'),
  requesterCur: Filter.requesterCur,
  requesters: Filter.requesters === null ? null : Filter.requesters.get('id'),
  companyCur: Filter.companyCur,
  companies: Filter.companies === null ? null : Filter.companies.get('id'),
  taskTypes: Filter.taskTypes === null ? null : Filter.taskTypes.get('id'),
  oneOf: Filter.oneOf,

  statusDateFrom: Filter.statusDateFrom,
  statusDateFromNow: Filter.statusDateFromNow,
  statusDateTo: Filter.statusDateTo,
  statusDateToNow: Filter.statusDateToNow,
  pendingDateFrom: Filter.pendingDateFrom,
  pendingDateFromNow: Filter.pendingDateFromNow,
  pendingDateTo: Filter.pendingDateTo,
  pendingDateToNow: Filter.pendingDateToNow,
  closeDateFrom: Filter.closeDateFrom,
  closeDateFromNow: Filter.closeDateFromNow,
  closeDateTo: Filter.closeDateTo,
  closeDateToNow: Filter.closeDateToNow,
  deadlineFrom: Filter.deadlineFrom,
  deadlineFromNow: Filter.deadlineFromNow,
  deadlineTo: Filter.deadlineTo,
  deadlineToNow: Filter.deadlineToNow,
  scheduledFrom: Filter.scheduledFrom,
  scheduledFromNow: Filter.scheduledFromNow,
  scheduledTo: Filter.scheduledTo,
  scheduledToNow: Filter.scheduledToNow,
  createdAtFrom: Filter.createdAtFrom,
  createdAtFromNow: Filter.createdAtFromNow,
  createdAtTo: Filter.createdAtTo,
  createdAtToNow: Filter.createdAtToNow,
})
